### ISSUE TITLE
[유저도메인]User도메인의 어노테이션 수정

### ISSUE THREAD

**Issue by RudinP** [Team-2m4t/Hyangyu-server#14]
## 문제 상황
> [참고블로그](https://kafcamus.tistory.com/15) 를 보니 @column의 nullable=false 보다는 @NotNull이 안전하다고 합니다~

## 해결 방법
> @Column->@NotNull로 변경

## 진행 상황
- [ ] 유저 도메인 @Column을 @NotNull 로 변경하기

**Comment by kiiiyeon** [comment]
우와 난 두 개 똑같은건줄ㅋㅋㅋㅋ 좋은자료네여 나도 보러감!!
