### ISSUE TITLE
[리뷰] 리뷰의 닉네임 필드 삭제

### ISSUE THREAD

**Issue by yujin113** [Team-2m4t/Hyangyu-server#73]
## 문제 상황
> 리뷰 테이블에 닉네임 필드 다 빼겠습니다.... 닉네임을 저장해버리면 나중에 유저가 닉네임 변경했을 때 적용이 안되는 문제가 생기더라구요

## 해결 방법
> 도메인에서 필드 빼기
> db에도 반영하기
> 리뷰 조회 시 nickname 필드 말고 유저 닉네임으로 끌고오기

**Comment by kiiiyeon** [comment]
아 맞아 이거 기획발표회 끝나고 리팩토링 하자고 할라그랬는데ㅜ!!
유진이 홧팅!!!
